version: '3'
services:

  # nginx:
  #   image: nginx:1.21.6
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - backend_latest
  #     - osrm_service
  #   networks:
  #     - alba_scl_wee
  #   ports:
  #     - 8000:8000

  test_pipeline_run:
    image: 946627858531.dkr.ecr.us-east-2.amazonaws.com/research-kedro-microservice:latest
    env_file: ../.env
    ports:
      - 8000:8000
    # command: bash -c "kedro test"
    command: bash -c "gunicorn
      --bind 0.0.0.0:8000 src.backend.main:app
      --log-config ./local_log_config.ini
      --workers 4
      -k uvicorn.workers.UvicornWorker
      --timeout 1800"
