name: Backend linting check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

    linting-check:

    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v2

      - name: Set up Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Building test environment
        run: bash -c "make env_install_dependencies"

      - name: Execution of pre-commit hooks over all files
        run: bash -c "pre-commit run --all-files"
