name: Build & Deployment to test

on:
  push:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v2

      - name: Image tag extraction from timestamp
        uses: josStorer/get-current-time@v2
        id: build-tag
        with:
          format: YYYY-MM-DD--HH-mm-ss
          utcOffset: "+00:00"

      - name: Image tag show
        env:
          build_tag: ${{ steps.build-tag.outputs.formattedTime }}
        run: echo $build_tag

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push to AWS ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.build-tag.outputs.formattedTime }}
        run: |
          docker build -f docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --no-cache --force-rm .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    outputs:
      build_tag: ${{ steps.build-tag.outputs.formattedTime }}


  deployment:

    runs-on: ubuntu-22.04
    needs: [build]
    strategy:
      matrix:
        infrastructure-components: [
          "terraform/rest_services/autoscaling_group",
          "terraform/pipelines/aws_batch",
        ]

    steps:

      - uses: actions/checkout@v2

      - name: "Setup AWS Credentials"
        run: |
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
            echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: ${{ matrix.infrastructure-components }} terraform init
        env:
          TF_WORKSPACE: test
        id: init
        run: cd ${{ matrix.infrastructure-components }} && terraform init

      - name: ${{ matrix.infrastructure-components }} terraform plan
        env:
          TF_VAR_software_build_version: ${{ needs.build.outputs.build_tag }}
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_WORKSPACE: test
          TF_VAR_google_maps_key:  ${{ secrets.GOOGLE_MAPS_KEY }}
        id: plan
        run: cd ${{ matrix.infrastructure-components }} && make plan

      - name: ${{ matrix.infrastructure-components }} terraform plan check
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: ${{ matrix.infrastructure-components }} terraform apply
        env:
          TF_VAR_software_build_version: latest
          TF_VAR_aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_WORKSPACE: test
          TF_VAR_google_maps_key:  ${{ secrets.GOOGLE_MAPS_KEY }}
        run: cd ${{ matrix.infrastructure-components }} && make apply
